In [83]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [84]:
from sklearn.model_selection import train_test_split

from sklearn.impute import KNNImputer,SimpleImputer
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import accuracy_score

In [85]:
df = np.round(pd.read_csv('50_Startups.csv')[['R&D Spend','Administration','Marketing Spend','Profit']]/1000)
df

    R&D Spend  Administration  Marketing Spend  Profit
0       165.0           137.0            472.0   192.0
1       163.0           151.0            444.0   192.0
2       153.0           101.0            408.0   191.0
3       144.0           119.0            383.0   183.0
4       142.0            91.0            366.0   166.0
5       132.0           100.0            363.0   157.0
6       135.0           147.0            128.0   156.0
7       130.0           146.0            324.0   156.0
8       121.0           149.0            312.0   152.0
9       123.0           109.0            305.0   150.0
10      102.0           111.0            229.0   146.0
11      101.0            92.0            250.0   144.0
12       94.0           127.0            250.0   142.0
13       92.0           135.0            253.0   134.0
14      120.0           157.0            257.0   133.0
15      115.0           123.0            262.0   130.0
16       78.0           122.0            264.0   127.0
17       95.0           145.0            283.0   125.0
18       92.0           114.0            295.0   124.0
19       86.0           154.0              0.0   123.0
20       76.0           114.0            299.0   118.0
21       78.0           154.0            300.0   111.0
22       74.0           123.0            303.0   110.0
23       68.0           106.0            305.0   109.0
24       77.0            99.0            141.0   109.0
25       65.0           140.0            138.0   107.0
26       75.0           144.0            134.0   106.0
27       72.0           128.0            353.0   105.0
28       66.0           183.0            118.0   103.0
29       66.0           153.0            107.0   101.0
30       62.0           116.0             91.0   100.0
31       61.0           153.0             88.0    97.0
32       63.0           129.0             46.0    97.0
33       55.0           103.0            215.0    97.0
34       46.0           158.0            211.0    97.0
35       46.0            85.0            206.0    96.0
36       29.0           127.0            201.0    91.0
37       44.0            51.0            197.0    90.0
38       20.0            66.0            185.0    81.0
39       39.0            83.0            175.0    81.0
40       29.0           119.0            173.0    78.0
41       28.0            85.0            164.0    78.0
42       24.0            96.0            148.0    71.0
43       16.0           127.0             36.0    70.0
44       22.0           155.0             28.0    65.0
45        1.0           124.0              2.0    65.0
46        1.0           116.0            297.0    49.0
47        0.0           135.0              0.0    43.0
48        1.0            52.0              0.0    36.0
49        0.0           117.0             45.0    15.0

In [86]:
df.shape

(50, 4)

In [87]:
df.iloc[1,0] = np.NaN
df.iloc[3,1] = np.NaN
df.iloc[-1,2] = np.NaN

In [88]:
# explicitly require this experimental feature
from sklearn.experimental import enable_iterative_imputer  # noqa
# now you can import normally from sklearn.impute
from sklearn.impute import IterativeImputer

In [89]:
X = df.drop(columns=['Profit'])
y = df['Profit']

In [90]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)

In [91]:
X_train

    R&D Spend  Administration  Marketing Spend
24       77.0            99.0            141.0
48        1.0            52.0              0.0
17       95.0           145.0            283.0
12       94.0           127.0            250.0
27       72.0           128.0            353.0
33       55.0           103.0            215.0
16       78.0           122.0            264.0
2       153.0           101.0            408.0
25       65.0           140.0            138.0
14      120.0           157.0            257.0
30       62.0           116.0             91.0
5       132.0           100.0            363.0
32       63.0           129.0             46.0
1         NaN           151.0            444.0
29       66.0           153.0            107.0
35       46.0            85.0            206.0
41       28.0            85.0            164.0
19       86.0           154.0              0.0
37       44.0            51.0            197.0
10      102.0           111.0            229.0
4       142.0            91.0            366.0
6       135.0           147.0            128.0
3       144.0             NaN            383.0
20       76.0           114.0            299.0
26       75.0           144.0            134.0
38       20.0            66.0            185.0
21       78.0           154.0            300.0
42       24.0            96.0            148.0
31       61.0           153.0             88.0
34       46.0           158.0            211.0
7       130.0           146.0            324.0
49        0.0           117.0              NaN
11      101.0            92.0            250.0
18       92.0           114.0            295.0
43       16.0           127.0             36.0
22       74.0           123.0            303.0
8       121.0           149.0            312.0
45        1.0           124.0              2.0
15      115.0           123.0            262.0
40       29.0           119.0            173.0

In [92]:
y_train

24    109.0
48     36.0
17    125.0
12    142.0
27    105.0
33     97.0
16    127.0
2     191.0
25    107.0
14    133.0
30    100.0
5     157.0
32     97.0
1     192.0
29    101.0
35     96.0
41     78.0
19    123.0
37     90.0
10    146.0
4     166.0
6     156.0
3     183.0
20    118.0
26    106.0
38     81.0
21    111.0
42     71.0
31     97.0
34     97.0
7     156.0
49     15.0
11    144.0
18    124.0
43     70.0
22    110.0
8     152.0
45     65.0
15    130.0
40     78.0
Name: Profit, dtype: float64

In [93]:
from sklearn.linear_model import LinearRegression

In [94]:

ii = IterativeImputer(estimator=LinearRegression(), max_iter=10, random_state=0)

X_train_trf2 = ii.fit_transform(X_train)
X_test_trf2 = ii.transform(X_test)